services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trading_competition
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://trading_user:${DB_PASSWORD}@postgres/trading_competition
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ""
      NEXT_PUBLIC_WS_URL: /ws/v1/market-data
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs

volumes:
  postgres_data:
  redis_data:
