name: CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: ~/.local/bin/uv sync
      - name: Run ruff
        run: ~/.local/bin/uv run ruff check .
      - name: Run mypy
        run: ~/.local/bin/uv run mypy src
      - name: Run tests
        run: ~/.local/bin/uv run pytest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Run ESLint
        run: pnpm lint
      - name: Run tests
        run: pnpm test -- --ci
      - name: Build
        run: pnpm build
